book=['On this day, prescribed by law and marked by ceremony, we celebrate the durable wisdom of our Constitution, and recall the deep commitments that unite our country. I am grateful for the honor of this hour, mindful of the consequential times in which we live, and determined to fulfill the oath that I have sworn and you have witnessed.'
'At this second gathering, our duties are defined not by the words I use, but by the history we have seen together. For a half century, America defended our own freedom by standing watch on distant borders. After the shipwreck of communism came years of relative quiet, years of repose, years of sabbatical —and then there came a day of fire.'
'We have seen our vulnerability —and we have seen its deepest source. For as long as whole regions of the world simmer in resentment and tyranny —prone to ideologies that feed hatred and excuse murder — violence will gather, and multiply in destructive power, and cross the most defended borders, and raise a mortal threat. There is only one force of history that can break the reign of hatred and resentment, and expose the pretensions of tyrants, and reward the hopes of the decent and tolerant, and that is the force of human freedom.'
'We are led, by events and common sense, to one conclusion: The survival of liberty in our land increasingly depends on the success of liberty in other lands. The best hope for peace in our world is the expansion of freedom in all the world.'
'Americas vital interests and our deepest beliefs are now one. From the day of our Founding, we have proclaimed that every man and woman on this earth has rights, and dignity, and matchless value, because they bear the image of the Maker of Heaven and earth. Across the generations we have proclaimed the imperative of self-government, because no one is fit to be a master, and no one deserves to be a slave. Advancing these ideals is the mission that created our Nation. It is the honorable achievement of our fathers. Now it is the urgent requirement of our nations security, and the calling of our time.'
'So it is the policy of the United States to seek and support the growth of democratic movements and institutions in every nation and culture, with the ultimate goal of ending tyranny in our world.'
'This is not primarily the task of arms, though we will defend ourselves and our friends by force of arms when necessary. Freedom, by its nature, must be chosen, and defended by citizens, and sustained by the rule of law and the protection of minorities. And when the soul of a nation finally speaks, the institutions that arise may reflect customs and traditions very different from our own. America will not impose our own style of government on the unwilling. Our goal instead is to help others find their own voice, attain their own freedom, and make their own way.'
'The great objective of ending tyranny is the concentrated work of generations. The difficulty of the task is no excuse for avoiding it. Americas influence is not unlimited, but fortunately for the oppressed, Americas influence is considerable, and we will use it confidently in freedoms cause.'
'My most solemn duty is to protect this nation and its people against further attacks and emerging threats. Some have unwisely chosen to test Americas resolve, and have found it firm.'
'We will persistently clarify the choice before every ruler and every nation: The moral choice between oppression, which is always wrong, and freedom, which is eternally right. America will not pretend that jailed dissidents prefer their chains, or that women welcome humiliation and servitude, or that any human being aspires to live at the mercy of bullies.'
'We will encourage reform in other governments by making clear that success in our relations will require the decent treatment of their own people. Americas belief in human dignity will guide our policies, yet rights must be more than the grudging concessions of dictators; they are secured by free dissent and the participation of the governed. In the long run, there is no justice without freedom, and there can be no human rights without human liberty.'
'Some, I know, have questioned the global appeal of liberty —though this time in history, four decades defined by the swiftest advance of freedom ever seen, is an odd time for doubt. Americans, of all people, should never be surprised by the power of our ideals. Eventually, the call of freedom comes to every mind and every soul. We do not accept the existence of permanent tyranny because we do not accept the possibility of permanent slavery. Liberty will come to those who love it.'
'Today, America speaks anew to the peoples of the world:'
'All who live in tyranny and hopelessness can know: the United States will not ignore your oppression, or excuse your oppressors. When you stand for your liberty, we will stand with you.'
'Democratic reformers facing repression, prison, or exile can know: America sees you for who you are: the future leaders of your free country.'
'The rulers of outlaw regimes can know that we still believe as Abraham Lincoln did: Those who deny freedom to others deserve it not for themselves; and, under the rule of a just God, cannot long retain it.'
'The leaders of governments with long habits of control need to know: To serve your people you must learn to trust them. Start on this journey of progress and justice, and America will walk at your side.'
'And all the allies of the United States can know: we honor your friendship, we rely on your counsel, and we depend on your help. Division among free nations is a primary goal of freedoms enemies. The concerted effort of free nations to promote democracy is a prelude to our enemies defeat.'
'Today, I also speak anew to my fellow citizens:'
'From all of you, I have asked patience in the hard task of securing America, which you have granted in good measure. Our country has accepted obligations that are difficult to fulfill, and would be dishonorable to abandon. Yet because we have acted in the great liberating tradition of this nation, tens of millions have achieved their freedom. And as hope kindles hope, millions more will find it. By our efforts, we have lit a fire as well —a fire in the minds of men. It warms those who feel its power, it burns those who fight its progress, and one day this untamed fire of freedom will reach the darkest corners of our world.'
'A few Americans have accepted the hardest duties in this cause —in the quiet work of intelligence and diplomacy ... the idealistic work of helping raise up free governments the dangerous and necessary work of fighting our enemies. Some have shown their devotion to our country in deaths that honored their whole lives —and we will always honor their names and their sacrifice.'
'All Americans have witnessed this idealism, and some for the first time. I ask our youngest citizens to believe the evidence of your eyes. You have seen duty and allegiance in the determined faces of our soldiers. You have seen that life is fragile, and evil is real, and courage triumphs. Make the choice to serve in a cause larger than your wants, larger than yourself —and in your days you will add not just to the wealth of our country, but to its character.'
'America has need of idealism and courage, because we have essential work at home —the unfinished work of American freedom. In a world moving toward liberty, we are determined to show the meaning and promise of liberty.'
'In Americas ideal of freedom, citizens find the dignity and security of economic independence, instead of laboring on the edge of subsistence. This is the broader definition of liberty that motivated the Homestead Act, the Social Security Act, and the G.I. Bill of Rights. And now we will extend this vision by reforming great institutions to serve the needs of our time. To give every American a stake in the promise and future of our country, we will bring the highest standards to our schools, and build an ownership society. We will widen the ownership of homes and businesses, retirement savings and health insurance —preparing our people for the challenges of life in a free society. By making every citizen an agent of his or her own destiny, we will give our fellow Americans greater freedom from want and fear, and make our society more prosperous and just and equal.'
'In Americas ideal of freedom, the public interest depends on private character —on integrity, and tolerance toward others, and the rule of conscience in our own lives. Self-government relies, in the end, on the governing of the self. That edifice of character is built in families, supported by communities with standards, and sustained in our national life by the truths of Sinai, the Sermon on the Mount, the words of the Koran, and the varied faiths of our people. Americans move forward in every generation by reaffirming all that is good and true that came before —ideals of justice and conduct that are the same yesterday, today, and forever.'
'In Americas ideal of freedom, the exercise of rights is ennobled by service, and mercy, and a heart for the weak. Liberty for all does not mean independence from one another. Our nation relies on men and women who look after a neighbor and surround the lost with love. Americans, at our best, value the life we see in one another, and must always remember that even the unwanted have worth. And our country must abandon all the habits of racism, because we cannot carry the message of freedom and the baggage of bigotry at the same time.'
'From the perspective of a single day, including this day of dedication, the issues and questions before our country are many. From the viewpoint of centuries, the questions that come to us are narrowed and few. Did our generation advance the cause of freedom? And did our character bring credit to that cause?'
'These questions that judge us also unite us, because Americans of every party and background, Americans by choice and by birth, are bound to one another in the cause of freedom. We have known divisions, which must be healed to move forward in great purposes —and I will strive in good faith to heal them. Yet those divisions do not define America. We felt the unity and fellowship of our nation when freedom came under attack, and our response came like a single hand over a single heart. And we can feel that same unity and pride whenever America acts for good, and the victims of disaster are given hope, and the unjust encounter justice, and the captives are set free.'
'We go forward with complete confidence in the eventual triumph of freedom. Not because history runs on the wheels of inevitability; it is human choices that move events. Not because we consider ourselves a chosen nation; God moves and chooses as He wills. We have confidence because freedom is the permanent hope of mankind, the hunger in dark places, the longing of the soul. When our Founders declared a new order of the ages; when soldiers died in wave upon wave for a union based on liberty; when citizens marched in peaceful outrage under the banner "Freedom Now" —they were acting on an ancient hope that is meant to be fulfilled. History has an ebb and flow of justice, but history also has a visible direction, set by liberty and the Author of Liberty.'
'When the Declaration of Independence was first read in public and the Liberty Bell was sounded in celebration, a witness said, It rang as if it meant something. In our time it means something still. America, in this young century, proclaims liberty throughout all the world, and to all the inhabitants thereof. Renewed in our strength — tested, but not weary — we are ready for the greatest achievements in the history of freedom.'
'May God bless you, and may He watch over the United States of America.']
      
reaganBook=[
'This day has been made brighter with the presence here of one who, for a time, has been absent - Senator John Stennis.'
'God bless you and welcome back.'
'There is, however, one who is not with us today: Representative Gillis Long of Louisiana left us last night. I wonder if we could all join in a moment of silent prayer. (Moment of silent prayer.) Amen.'
'There are no words adequate to express my thanks for the great honor that you have bestowed on me. I will do my utmost to be deserving of your trust.'
'This is, as Senator Mathias told us, the 50th time that we the people have celebrated this historic occasion. When the first President, George Washington, placed his hand upon the Bible, he stood less than a single days journey by horseback from raw, untamed wilderness. There were 4 million Americans in a union of 13 States. Today we are 60 times as many in a union of 50 States. We have lighted the world with our inventions, gone to the aid of mankind wherever in the world there was a cry for help, journeyed to the Moon and safely returned. So much has changed. And yet we stand together as we did two centuries ago.'
'When I took this oath four years ago, I did so in a time of economic stress. Voices were raised saying we had to look to our past for the greatness and glory. But we, the present-day Americans, are not given to looking backward. In this blessed land, there is always a better tomorrow.'
'Four years ago, I spoke to you of a new beginning and we have accomplished that. But in another sense, our new beginning is a continuation of that beginning created two centuries ago when, for the first time in history, government, the people said, was not our master, it is our servant; its only power that which we the people allow it to have.'
'That system has never failed us, but, for a time, we failed the system. We asked things of government that government was not equipped to give. We yielded authority to the National Government that properly belonged to States or to local governments or to the people themselves. We allowed taxes and inflation to rob us of our earnings and savings and watched the great industrial machine that had made us the most productive people on Earth slow down and the number of unemployed increase.'
'By 1980, we knew it was time to renew our faith, to strive with all our strength toward the ultimate in individual freedom consistent with an orderly society.'
'We believed then and now there are no limits to growth and human progress when men and women are free to follow their dreams.'
'And we were right to believe that. Tax rates have been reduced, inflation cut dramatically, and more people are employed than ever before in our history.'
'We are creating a nation once again vibrant, robust, and alive. But there are many mountains yet to climb. We will not rest until every American enjoys the fullness of freedom, dignity, and opportunity as our birthright. It is our birthright as citizens of this great Republic, and well meet this challenge.'
'These will be years when Americans have restored their confidence and tradition of progress; when our values of faith, family, work, and neighborhood were restated for a modern age; when our economy was finally freed from governments grip; when we made sincere efforts at meaningful arms reduction, rebuilding our defenses, our economy, and developing new technologies, and helped preserve peace in a troubled world; when Americans courageously supported the struggle for liberty, self-government, and free enterprise throughout the world, and turned the tide of history away from totalitarian darkness and into the warm sunlight of human freedom.'
'My fellow citizens, our Nation is poised for greatness. We must do what we know is right and do it with all our might. Let history say of us, These were golden years - when the American Revolution was reborn, when freedom gained new life, when America reached for her best.'
'Our two-party system has served us well over the years, but never better than in those times of great challenge when we came together not as Democrats or Republicans, but as Americans united in a common cause.'
'Two of our Founding Fathers, a Boston lawyer named Adams and a Virginia planter named Jefferson, members of that remarkable group who met in Independence Hall and dared to think they could start the world over again, left us an important lesson. They had become political rivals in the Presidential election of 1800. Then years later, when both were retired, and age had softened their anger, they began to speak to each other again through letters. A bond was reestablished between those two who had helped create this government of ours.'
'In 1826, the 50th anniversary of the Declaration of Independence, they both died. They died on the same day, within a few hours of each other, and that day was the Fourth of July.'
'In one of those letters exchanged in the sunset of their lives, Jefferson wrote: It carries me back to the times when, beset with difficulties and dangers, we were fellow laborers in the same cause, struggling for what is most valuable to man, his right to self-government. Laboring always at the same oar, with some wave ever ahead threatening to overwhelm us, and yet passing harmless ... we rode through the storm with heart and hand.'
'Well, with heart and hand, let us stand as one today: One people under God determined that our future shall be worthy of our past. As we do, we must not repeat the well-intentioned errors of our past. We must never again abuse the trust of working men and women, by sending their earnings on a futile chase after the spiraling demands of a bloated Federal Establishment. You elected us in 1980 to end this prescription for disaster, and I dont believe you reelected us in 1984 to reverse course.'
'At the heart of our efforts is one idea vindicated by 25 straight months of economic growth: Freedom and incentives unleash the drive and entrepreneurial genius that are the core of human progress. We have begun to increase the rewards for work, savings, and investment; reduce the increase in the cost and size of government and its interference in peoples lives.'
'We must simplify our tax system, make it more fair, and bring the rates down for all who work and earn. We must think anew and move with a new boldness, so every American who seeks work can find work; so the least among us shall have an equal chance to achieve the greatest things - to be heroes who heal our sick, feed the hungry, protect peace among nations, and leave this world a better place.'
'The time has come for a new American emancipation - a great national drive to tear down economic barriers and liberate the spirit of enterprise in the most distressed areas of our country. My friends, together we can do this, and do it we must, so help me God.'
'From new freedom will spring new opportunities for growth, a more productive, fulfilled and united people, and a stronger America - an America that will lead the technological revolution, and also open its mind and heart and soul to the treasures of literature, music, and poetry, and the values of faith, courage, and love.'
'A dynamic economy, with more citizens working and paying taxes, will be our strongest tool to bring down budget deficits. But an almost unbroken 50 years of deficit spending has finally brought us to a time of reckoning. We have come to a turning point, a moment for hard decisions. I have asked the Cabinet and my staff a question, and now I put the same question to all of you: If not us, who? And if not now, when? It must be done by all of us going forward with a program aimed at reaching a balanced budget. We can then begin reducing the national debt.'
'I will shortly submit a budget to the Congress aimed at freezing government program spending for the next year. Beyond that, we must take further steps to permanently control Governments power to tax and spend. We must act now to protect future generations from Governments desire to spend its citizens money and tax them into servitude when the bills come due. Let us make it unconstitutional for the Federal Government to spend more than the Federal Government takes in.'
'We have already started returning to the people and to State and local governments responsibilities better handled by them. Now, there is a place for the Federal Government in matters of social compassion. But our fundamental goals must be to reduce dependency and upgrade the dignity of those who are infirm or disadvantaged. And here a growing economy and support from family and community offer our best chance for a society where compassion is a way of life, where the old and infirm are cared for, the young and, yes, the unborn protected, and the unfortunate looked after and made self-sufficient.'
'And there is another area where the Federal Government can play a part. As an older American, I remember a time when people of different race, creed, or ethnic origin in our land found hatred and prejudice installed in social custom and, yes, in law. There is no story more heartening in our history than the progress that we have made toward the "brotherhood of man" that God intended for us. Let us resolve there will be no turning back or hesitation on the road to an America rich in dignity and abundant with opportunity for all our citizens.'
'Let us resolve that we the people will build an American opportunity society in which all of us - white and black, rich and poor, young and old - will go forward together arm in arm. Again, let us remember that though our heritage is one of blood lines from every corner of the Earth, we are all Americans pledged to carry on this last, best hope of man on Earth.'
'I have spoken of our domestic goals and the limitations which we should put on our National Government. Now let me turn to a task which is the primary responsibility of National Government - the safety and security of our people.'
'Today, we utter no prayer more fervently than the ancient prayer for peace on Earth. Yet history has shown that peace will not come, nor will our freedom be preserved, by good will alone. There are those in the world who scorn our vision of human dignity and freedom. One nation, the Soviet Union, has conducted the greatest military buildup in the history of man, building arsenals of awesome offensive weapons.'
'We have made progress in restoring our defense capability. But much remains to be done. There must be no wavering by us, nor any doubts by others, that America will meet her responsibilities to remain free, secure, and at peace.'
'There is only one way safely and legitimately to reduce the cost of national security, and that is to reduce the need for it. And this we are trying to do in negotiations with the Soviet Union. We are not just discussing limits on a further increase of nuclear weapons. We seek, instead, to reduce their number. We seek the total elimination one day of nuclear weapons from the face of the Earth.'
'Now, for decades, we and the Soviets have lived under the threat of mutual assured destruction; if either resorted to the use of nuclear weapons, the other could retaliate and destroy the one who had started it. Is there either logic or morality in believing that if one side threatens to kill tens of millions of our people, our only recourse is to threaten killing tens of millions of theirs?'
'I have approved a research program to find, if we can, a security shield that would destroy nuclear missiles before they reach their target. It wouldnt kill people, it would destroy weapons. It wouldnt militarize space, it would help demilitarize the arsenals of Earth. It would render nuclear weapons obsolete. We will meet with the Soviets, hoping that we can agree on a way to rid the world of the threat of nuclear destruction.'
'We strive for peace and security, heartened by the changes all around us. Since the turn of the century, the number of democracies in the world has grown fourfold. Human freedom is on the march, and nowhere more so than our own hemisphere. Freedom is one of the deepest and noblest aspirations of the human spirit. People, worldwide, hunger for the right of self-determination, for those inalienable rights that make for human dignity and progress.'
'America must remain freedoms staunchest friend, for freedom is our best ally.'
'And it is the worlds only hope, to conquer poverty and preserve peace. Every blow we inflict against poverty will be a blow against its dark allies of oppression and war. Every victory for human freedom will be a victory for world peace.'
'So we go forward today, a nation still mighty in its youth and powerful in its purpose. With our alliances strengthened, with our economy leading the world to a new age of economic expansion, we look forward to a world rich in possibilities. And all this because we have worked and acted together, not as members of political parties, but as Americans.'
'My friends, we live in a world that is lit by lightning. So much is changing and will change, but so much endures, and transcends time.'
'History is a ribbon, always unfurling; history is a journey. And as we continue our journey, we think of those who traveled before us. We stand together again at the steps of this symbol of our democracy - or we would have been standing at the steps if it hadnt gotten so cold. Now we are standing inside this symbol of our democracy. Now we hear again the echoes of our past: a general falls to his knees in the hard snow of Valley Forge; a lonely President paces the darkened halls, and ponders his struggle to preserve the Union; the men of the Alamo call out encouragement to each other; a settler pushes west and sings a song, and the song echoes out forever and fills the unknowing air.'
'It is the American sound. It is hopeful, big-hearted, idealistic, daring, decent, and fair. Thats our heritage; that is our song. We sing it still. For all our problems, our differences, we are together as of old, as we raise our voices to the God who is the Author of this most tender music. And may He continue to hold us close as we fill the world with our sound - sound in unity, affection, and love - one people under God, dedicated to the dream of freedom that He has placed in the human heart, called upon now to pass that dream on to a waiting and hopeful world.'
'God bless you and may God bless America.']

d = dict()
for i in range(0,len(book)):
    for c in book[i].split():
        if c not in d:
            d[c]=1
        else:
            d[c]+=1
b = dict()
for i in range(0,len(reaganBook)):
    for c in reaganBook[i].split():
        if c not in b:
            b[c]=1
        else:
            b[c]+=1

print "Bush의 취임사중:"
for i in d:
    if d[i]>23:
        print i, d[i]
print "Reagan의 취임사중:"
for i in b:
    if b[i]>29:
        print i, b[i]